Add AppBar in Application
karibu-cap/trans_all_client pull request #45
Opened 2023-09-06 15:08 UTC by YvanNjanko

2023-09-06 18:01 UTC, nidovic commented on common/internationalization/lib/src/app_internationalization.dart
> +  /// cle TransAll.
```suggestion
  /// Returns the localized value of TransAll.
```

2023-09-06 20:45 UTC, warrenrhodes requested changes

2023-09-06 20:45 UTC, warrenrhodes commented on app_customers/lib/main.dart
> +      builder: (context, child) {
Make it here will be displayed on all our pages; we don't want it. we have our custom scaffold widget  https://github.com/karibu-cap/trans_all_client/blob/bafee67f8bb8ae849311465a9aa7c1dd7a769070/app_customers/lib/widgets/custom_scaffold.dart#L9

2023-09-11 19:54 UTC, warrenrhodes approved these changes

2023-09-11 20:16 UTC, merged